Repository PlanBCode/hypha, pull requests merged in 2019-04, with the labels that each got.

#223 Adds help icon for choosing new page type
  system/core/pages.php
  system/languages/en.php
  system/languages/nl.php
Labels: Status: Ready to merge

#224 Sloppy language
  index.php
  system/core/users.php
  system/datatypes/mailinglist.php
  system/languages/en.php
  system/languages/nl.php
Labels: Status: Ready to merge

#227 Comment unanonymous 2
  data/themes/default/hypha.css
  system/datatypes/peer_reviewed_article.php
  system/languages/en.php
  system/languages/nl.php
Labels: Status: Ready to merge

#243 Adds a help icon with rules for civil discussion in comments
  system/datatypes/peer_reviewed_article.php
  system/languages/en.php
  system/languages/nl.php
Labels: Status: Needs review, Type: Enhancement, Usecase: De Stadsbron, Value: Users, Value: Visitors

#219 Remove cols and rows attributes from comment textareas
  data/themes/default/hypha.css
  system/datatypes/peer_reviewed_article.php
Labels: Status: Needs changes

#228 Different labels for new discussions and replies
  system/datatypes/peer_reviewed_article.php
  system/languages/en.php
  system/languages/nl.php
Labels: Status: Needs changes, Status: Needs review

#218 Adds an explanation to the quit page
  system/datatypes/settings.php
  system/languages/en.php
  system/languages/nl.php
Labels: status: has conflicts
