Repository PlanBCode/hypha, pull requests merged in 2020-03, with the labels that each got.

#252 Use language.php instead of dummy (only english) language
  hypha.php
  system/core/language.php
  system/languages/languages.json
Labels: Status: Ready to merge

#292 textpage: Clean up
  system/datatypes/text.php
Labels: Status: Needs review

#254 Feature: Make default page type configurable
  index.php
  system/core/base.php
  system/core/pages.php
  system/datatypes/settings.php
  system/languages/en.php
  system/languages/nl.php
Labels: Status: Needs review

#280 Language selection
  index.php
  system/core/HyphaRequest.php
  system/core/RequestContext.php
  system/core/base.php
  system/core/language.php
  system/core/pages.php
  system/datatypes/peer_reviewed_article.php
  system/datatypes/settings.php
  system/datatypes/text.php
  system/languages/en.php
  system/languages/nl.php
  system/php-dom-wrapper/Traits/ManipulationTrait.php
  tests/HyphaRequestTest.php
Labels: Status: Needs changes

#281 Peer reviewed article subscribe to discussion updates
  system/datatypes/peer_reviewed_article.php
  system/languages/en.php
  system/languages/nl.php
Labels: Status: Needs review
